---
gig1: "192.2.1.1 255.255.255.0"
gig2: "192.2.2.1 255.255.255.0"
gig1_description: "WAN Interface"
gig2_description: "LAN Interface"
loopback0: "22.22.22.22 255.255.255.255"
loopback0_description: "Source Loopback"
ospf_network_all: "network 0.0.0.0 0.0.0.0 area 0"
ospf_network_update_source: "router-id 22.22.22.22"
router_id: "22.22.22.22"
bgp_neighbor_1: "192.2.1.2"
